apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-webhook-production
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - name: github-production-trigger
      bindings:
        - ref: github-webhook-triggerbinding
      template:
        ref: github-webhook-triggertemplate
      interceptors:
        - name: verify-github-payload
          ref:
            name: github
          params:
            - name: secretRef
              value:
                secretName: github-webhook-secret
                secretKey: webhook-secret
            - name: eventTypes
              value: ["push", "pull_request"]
