apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: pytest-trigger-template
  namespace: tekton-pipelines
spec:
  params:
    - name: git-url
      description: Git repository URL
    - name: git-revision
      description: Git revision to checkout
    - name: repo-name
      description: Repository name
    - name: commit-message
      description: Commit message
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: pytest-run-
        namespace: tekton-pipelines
        labels:
          tekton.dev/pipeline: pytest-pipeline
          app.kubernetes.io/managed-by: tekton-triggers
          app.kubernetes.io/part-of: tekton-poc
          git-repo: $(tt.params.repo-name)
          git-sha: $(tt.params.git-revision)
      spec:
        pipelineRef:
          name: pytest-pipeline
        params:
          - name: git-url
            value: $(tt.params.git-url)
          - name: git-revision
            value: $(tt.params.git-revision)
        workspaces:
          - name: shared-data
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
