apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: pytest-trigger-template
  namespace: default
spec:
  params:
    - name: git-url
      description: Git repository URL
    - name: git-revision
      description: Git revision to checkout
    - name: git-repo-name
      description: Repository name
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pytest-run-$(tt.params.git-revision)
        namespace: default
      spec:
        pipelineRef:
          name: pytest-pipeline
        params:
          - name: git-url
            value: $(tt.params.git-url)
          - name: git-revision
            value: $(tt.params.git-revision)
        workspaces:
          - name: shared-data
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
