apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pytest-pipeline
  namespace: tekton-pipelines
spec:
  description: CI/CD Pipeline for Python pytest POC
  params:
    - name: git-url
      type: string
      description: Git repository URL
      default: "https://github.com/johnnynv/tekton-poc.git"
    - name: git-revision
      type: string
      description: Git revision to checkout
      default: main
  workspaces:
    - name: shared-data
      description: Shared workspace for pipeline tasks
  tasks:
    - name: run-pytest-tests
      taskRef:
        name: pytest-task
      params:
        - name: git-url
          value: $(params.git-url)
        - name: git-revision
          value: $(params.git-revision)
      workspaces:
        - name: source
          workspace: shared-data
  finally:
    - name: show-test-reports-link
      params:
        - name: git-revision
          value: $(params.git-revision)
      taskSpec:
        params:
          - name: git-revision
        steps:
          - name: display-links
            image: alpine:latest
            script: |
              #!/bin/sh
              echo ""
              echo "🎉 ===== PYTEST EXECUTION COMPLETED ===== 🎉"
              echo ""
              echo "📊 Test Reports Web UI:"
              echo "🔗 http://10.117.3.193:30081"
              echo ""
              echo "📋 Available Reports:"
              echo "   📈 Full Test Report (HTML)"
              echo "   💨 Smoke Tests Report" 
              echo "   📊 Code Coverage Analysis"
              echo "   ⬇️  Downloadable Artifacts"
              echo ""
              echo "⏰ Reports server active for 10 minutes"
              echo "🎯 Git SHA: $(params.git-revision)"
              echo ""
              echo "🏠 Tekton Dashboard: http://tekton.10.117.3.193.nip.io"
              echo "=============================================="