apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: pytest-task
  namespace: tekton-pipelines
spec:
  description: Run pytest tests for the project
  # Pod Security Context for compliance with restricted security policy
  securityContext:
    runAsNonRoot: true
    runAsUser: 65532  # nonroot user
    runAsGroup: 65532
    seccompProfile:
      type: RuntimeDefault
    # Apply to all containers in the pod
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
  params:
    - name: git-url
      type: string
      description: Git repository URL
    - name: git-revision
      type: string
      description: Git revision to checkout
      default: main
  workspaces:
    - name: source
      description: The workspace containing the source code
  steps:
    - name: git-clone
      image: alpine/git:latest
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -e
        echo "Cloning repository $(params.git-url) at revision $(params.git-revision)"
        git clone $(params.git-url) .
        git checkout $(params.git-revision)
        echo "Repository cloned successfully"
        ls -la
    
    - name: run-python-tests
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        set -e
        
        # Install dependencies once
        echo "Installing Python dependencies..."
        pip install -r requirements.txt
        echo "Dependencies installed successfully"
        
        # Run all tests
        echo "Running all pytest tests..."
        python -m pytest tests/ -v --tb=short
        echo "All tests completed successfully"
        
        # Run smoke tests
        echo "Running smoke tests with -m marker..."
        python -m pytest tests/ -v --tb=short -m smoke
        echo "Smoke tests completed successfully"
        
        # Run main program
        echo "Running main program..."
        python main.py
        echo "Main program executed successfully"
