apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: pytest-task
  namespace: tekton-pipelines
spec:
  description: Run pytest tests for the project
  # Template for all steps (reduces repetition)
  stepTemplate:
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      runAsNonRoot: true
      runAsUser: 65532
      seccompProfile:
        type: RuntimeDefault
  params:
    - name: git-url
      type: string
      description: Git repository URL
    - name: git-revision
      type: string
      description: Git revision to checkout
      default: main
  workspaces:
    - name: source
      description: The workspace containing the source code
  steps:
    - name: git-clone
      image: alpine/git:latest
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -e
        echo "Cloning repository $(params.git-url) at revision $(params.git-revision)"
        
        # Disable Git ownership checks for this workspace
        export GIT_CONFIG_GLOBAL=""
        git config --global --add safe.directory '*' || true
        
        # Alternative: use environment variable to disable ownership checks
        export GIT_CEILING_DIRECTORIES=""
        
        # Clone and checkout with ownership checks disabled
        git -c safe.directory='*' clone $(params.git-url) .
        git -c safe.directory='*' checkout $(params.git-revision)
        echo "Repository cloned successfully"
        ls -la
    
    - name: run-python-tests
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        set -e
        
        # Install dependencies once
        echo "Installing Python dependencies..."
        pip install -r requirements.txt
        echo "Dependencies installed successfully"
        
        # Run all tests
        echo "Running all pytest tests..."
        python -m pytest tests/ -v --tb=short
        echo "All tests completed successfully"
        
        # Run smoke tests
        echo "Running smoke tests with -m marker..."
        python -m pytest tests/ -v --tb=short -m smoke
        echo "Smoke tests completed successfully"
        
        # Run main program
        echo "Running main program..."
        python main.py
        echo "Main program executed successfully"
